import type { Metadata } from 'next';
import LoginForm from '@/components/Auth/LoginForm';

export const metadata: Metadata = {
  title: 'Login Page',
  description: 'Generated by hy-next-js-template',
};

export default function LoginPage() {
  return <LoginForm />;
}
