import type { Metadata } from 'next';
import RegisterForm from '@/components/Auth/RegisterForm';

export const metadata: Metadata = {
  title: 'Register Page',
  description: 'Generated by hy-next-js-template',
};

export default function RegisterPage() {
  return <RegisterForm />;
}
