import type { Metadata } from 'next';
import ForgotPasswordForm from '@/components/Auth/ForgotPasswordForm';

export const metadata: Metadata = {
  title: 'Forgot Password Page',
  description: 'Generated by hy-next-js-template',
};

export default function ForgotPasswordPage() {
  return <ForgotPasswordForm />;
}
